name: nemeeting
description: A new Flutter application.
publish_to: none

version: 4.7.0+40700

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  archive: ^3.4.10
  convert: ^3.1.1
  flutter_datetime_picker: ^1.5.1
  async: ^2.11.0
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  package_info_plus: ^7.0.0
  dio: ^5.4.2+1
  pin_input_text_field: ^4.5.1
  url_launcher: ^6.2.6
  crypto: ^3.0.3

  netease_meeting_ui:
    path: ../meeting_kit_ui
  netease_common: ^1.0.6
  file_picker: ^8.0.0+1
  marvelflutter: ^0.0.2

  webview_flutter: ^4.7.0
  sensors_plus: ^5.0.1
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  mask_text_input_formatter: ^2.9.0
  device_info_plus: ^10.1.0
  device_information: ^0.0.4
  sticky_headers: ^0.3.0


# dependency_overrides:

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/virtual_background_images/images.zip
    - assets/lottie/

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

