name: netease_meeting_ui
description: A package implements standard UI for netease_meeting.
version: 0.0.1
homepage: https://yunxin.163.com/
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  device_info_plus: ^10.1.0

  azlistview_plus: ^3.0.0
  flutter_contacts: ^1.1.7
  lpinyin: ^2.0.3

  cupertino_icons: ^1.0.5

#  netease_meeting_assets: ^0.1.0-rc.0
  netease_meeting_assets:
    path: ../meeting_kit_assets
#  netease_common: ^0.0.3-rc.0
  netease_common: ^1.0.5

  bot_toast: ^4.1.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  wakelock_plus: ^1.2.4
  shared_preferences: ^2.2.3
  characters: ^1.3.0
  convert: ^3.1.1
  webview_flutter: ^4.7.0
  provider: ^6.1.2
  image_size_getter: ^2.1.3
  cached_network_image: ^3.3.1
  open_filex: ^4.4.0
  scrollable_positioned_list: ^0.3.8
  file_picker: ^8.0.0+1
  mask_text_input_formatter: ^2.9.0
  audioplayers: ^6.0.0

  netease_meeting_core:
    path: ../meeting_kit
  netease_roomkit: 1.28.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
  plugin:
    platforms:
      android:
        package: com.netease.meeting.plugin
        pluginClass: MeetingPlugin
      ios:
        pluginClass: MeetingPlugin
