name: build meeting flutter

on:
  push:
    paths:
      - 'meeting-flutter/**'
  pull_request:
    paths:
      - 'meeting-flutter/**'

jobs:
  build_android:
    name: Build for Android
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: pwd
      - run: ls -al
      - run: cd ./meeting-flutter/meeting-app
      - run: flutter pub get
      - run: flutter build apk

  build_iOS:
    name: Build for iOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - run: pwd
      - run: ls -al
      - run: cd meeting-flutter
      - run: pwd
      - run: ls -al
      - run: cd meeting-app
      - run: pwd
      #- run: cd ./meeting-flutter/meeting-app
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
